import { Button, Flex, Stack } from '@chakra-ui/react'
import Head from 'next/head'
import React from 'react'

import { Input } from "@/components/Form/Input"

export default function SignIn() {
  return (
    <>
      <Head>
        <title>Chakra APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex
          w="100vw"
          h="100vh"
          align="center"
          justify="center"
        >
          <Flex
            as="form"
            w="100%"
            maxW={360}
            bg="gray.800"
            p="8"
            borderRadius={8}
            flexDir="column"
          >
            <Stack spacing="4">

              <Input type="email" name="email" label="E-mail" />
              <Input type="password" name="password" label="Senha" />

            </Stack>
            <Button
              type='submit'
              mt="6"
              colorScheme='pink'
            >
              Entrar
            </Button>
          </Flex>
        </Flex>
      </main>
    </>
  )
}
